2020-02-20 17:54:28.265014: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/17.11.2/lib64/slurm:/cm/shared/apps/slurm/17.11.2/lib64:/cm/local/apps/gcc/6.1.0/lib:/cm/local/apps/gcc/6.1.0/lib64
2020-02-20 17:54:28.267503: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/17.11.2/lib64/slurm:/cm/shared/apps/slurm/17.11.2/lib64:/cm/local/apps/gcc/6.1.0/lib:/cm/local/apps/gcc/6.1.0/lib64
2020-02-20 17:54:28.267550: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/rigel/home/rcc2167/.conda/envs/gpflow6_0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/rigel/home/rcc2167/.conda/envs/gpflow6_0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/rigel/home/rcc2167/.conda/envs/gpflow6_0/lib/python3.6/site-packages/memory_profiler.py", line 1274, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "/rigel/home/rcc2167/.conda/envs/gpflow6_0/lib/python3.6/site-packages/memory_profiler.py", line 1175, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "readv_it.py", line 1064, in <module>
    readv()
  File "/rigel/home/rcc2167/.conda/envs/gpflow6_0/lib/python3.6/site-packages/memory_profiler.py", line 1113, in wrapper
    val = prof(func)(*args, **kwargs)
  File "/rigel/home/rcc2167/.conda/envs/gpflow6_0/lib/python3.6/site-packages/memory_profiler.py", line 699, in f
    return func(*args, **kwds)
  File "readv_it.py", line 122, in readv
    & (dfind.lat < extent[3])][[
  File "/rigel/home/rcc2167/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1229, in wrapper
    res = na_op(values, other)
  File "/rigel/home/rcc2167/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1117, in na_op
    return invalid_comparison(x, y, op)
  File "/rigel/home/rcc2167/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 497, in invalid_comparison
    dtype=left.dtype, typ=type(right).__name__
TypeError: Invalid comparison between dtype=int64 and str
